module Happyfunrun

	mattr_accessor :models
	@@models = []

	# A token generated by HappyFunRun that must be passed with all requests
	mattr_accessor :key
	@@key = ''

	def self.track_value_of(model_scope_or_proc, optiosn={})
		@@models << Subject.new(model_scope_or_proc, options)
	end

	def self.setup
	
		# User after_initialize so that model scopes may be accessed. Otherwise I ran into issues
		# where models which accessed config directly (e.g. paperclip + s3.yaml) were not initialized
		# by the time this was executed.
		
		Rails.application.config.after_initialize do
			yield self
		end
	end

	class Engine < Rails::Engine

	end
end
